version: '3'

services:
  jupyter:
    container_name: workshop
    image: ymiq/octopusai_ws:latest
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ./TFODAPI.ipynb:/hearts/TFODAPI.ipynb
      - ./test_notebook.ipynb:/hearts/test_notebook.ipynb
      - ./models_train:/hearts/models_train
      - ./dataset:/hearts/dataset
      - ./autoencoder_ws:/hearts/autoencoder_ws
      - ./imgs:/hearts/imgs
    working_dir: '/hearts'
    command: 'jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root'
