version: '3'

services:
  jupyter:
    container_name: workshop
    image: ymiq/octopusai_ws:latest
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - $PWD/TFODAPI.ipynb:/hearts/TFODAPI.ipynb
      - $PWD/models_train:/hearts/models_train
      - $PWD/dataset:/hearts/dataset
      - $PWD/autoencoder_ws:/hearts/autoencoder_ws
    working_dir: '/hearts'
    command: 'jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root'
